/** Supported video site domains */
const SUPPORTED_DOMAINS = [
  "youtube.com",
  "youtu.be",
  "bilibili.com",
  "b23.tv",
  "twitch.tv",
  "vimeo.com",
  "dailymotion.com",
  "nicovideo.jp",
  "twitter.com",
  "x.com",
  "instagram.com",
  "tiktok.com",
  "facebook.com",
  "fb.watch",
  "reddit.com",
  "soundcloud.com",
  "bandcamp.com",
  "crunchyroll.com",
];

/**
 * Check if a URL belongs to a supported video site
 * @param {string} url
 * @returns {boolean}
 */
function isSupportedSite(url) {
  try {
    const hostname = new URL(url).hostname;
    return SUPPORTED_DOMAINS.some((d) => hostname === d || hostname.endsWith("." + d));
  } catch {
    return false;
  }
}

/**
 * Convert a chrome.cookies.Cookie to Netscape format line
 * @param {chrome.cookies.Cookie} cookie
 * @returns {string}
 */
function toNetscapeLine(cookie) {
  const domain = cookie.domain.startsWith(".") ? cookie.domain : "." + cookie.domain;
  const flag = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
  return `${domain}\t${flag}\t${cookie.path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`;
}

/**
 * Get all cookies for a URL from the browser
 * @param {string} url
 * @returns {Promise<string>} Netscape format cookie text
 */
async function getCookies(url) {
  return new Promise((resolve) => {
    chrome.cookies.getAll({ url }, (cookies) => {
      if (!cookies || cookies.length === 0) {
        resolve("");
        return;
      }
      const header =
        "# Netscape HTTP Cookie File\n# Generated by SENTINNELL PLAY NOW Browser Extension\n\n";
      const lines = cookies.map(toNetscapeLine);
      resolve(header + lines.join("\n"));
    });
  });
}

// Initialize popup
document.addEventListener("DOMContentLoaded", async () => {
  const statusEl = document.getElementById("status");
  const statusText = document.getElementById("status-text");
  const urlPreview = document.getElementById("url-preview");
  const sendBtn = document.getElementById("send-btn");
  const sendCookiesToggle = document.getElementById("send-cookies");

  // Get current tab
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const pageUrl = tab?.url || "";

  if (!pageUrl || !isSupportedSite(pageUrl)) {
    statusEl.className = "status unsupported";
    statusText.textContent = "This site is not supported";
    sendBtn.disabled = true;
    return;
  }

  statusEl.className = "status supported";
  statusText.textContent = "Supported site detected";
  urlPreview.style.display = "block";
  urlPreview.textContent = pageUrl;
  sendBtn.disabled = false;

  sendBtn.addEventListener("click", async () => {
    sendBtn.disabled = true;
    document.getElementById("btn-text").textContent = "Sending...";

    try {
      const encodedUrl = encodeURIComponent(pageUrl);
      let deepLink = `ytdlp-gui://download?url=${encodedUrl}`;

      if (sendCookiesToggle.checked) {
        const cookieText = await getCookies(pageUrl);
        if (cookieText) {
          const base64Cookies = btoa(encodeURIComponent(cookieText));
          deepLink += `&cookies=${base64Cookies}`;
        }
      }

      window.open(deepLink, "_self");

      document.getElementById("btn-text").textContent = "Sent!";
      setTimeout(() => window.close(), 800);
    } catch (err) {
      document.getElementById("btn-text").textContent = "Failed, try again";
      sendBtn.disabled = false;
    }
  });
});
