<script setup lang="ts">
import { useI18n } from "vue-i18n";
import type { VideoInfo } from "@/types";

const { t } = useI18n();

const LANG_NAMES: Record<string, string> = {
  zh: "中文", "zh-Hans": "中文(简体)", "zh-Hant": "中文(繁体)",
  "zh-CN": "中文(简体)", "zh-TW": "中文(繁体)", "zh-HK": "中文(香港)",
  en: "English", "en-US": "English(US)", "en-GB": "English(UK)",
  ja: "日本語", ko: "한국어", fr: "Français", de: "Deutsch",
  es: "Español", pt: "Português", ru: "Русский", ar: "العربية",
  it: "Italiano", nl: "Nederlands", pl: "Polski", tr: "Türkçe",
  vi: "Tiếng Việt", th: "ไทย", id: "Bahasa Indonesia", ms: "Bahasa Melayu",
  hi: "हिन्दी", uk: "Українська", cs: "Čeština", sv: "Svenska",
  da: "Dansk", fi: "Suomi", no: "Norsk", el: "Ελληνικά",
  he: "עברית", hu: "Magyar", ro: "Română", bg: "Български",
};

/** 需要过滤的非字幕项 */
const FILTERED_KEYS = new Set(["live_chat"]);

const props = defineProps<{
  videoInfo: VideoInfo;
}>();

const selectedSubtitles = defineModel<string[]>("selectedSubtitles", {
  required: true,
});

/** 获取语言显示名称 */
const getLangLabel = (lang: string, tracks: { name?: string }[]): string => {
  const name = tracks[0]?.name;
  const mapped = LANG_NAMES[lang];
  if (name && mapped) return `${mapped} (${name})`;
  if (name) return `${name} (${lang})`;
  if (mapped) return mapped;
  return lang;
};

/** 手动上传的字幕选项 */
const manualOptions = computed(() =>
  Object.entries(props.videoInfo.subtitles || {})
    .filter(([lang]) => !FILTERED_KEYS.has(lang))
    .map(([lang, tracks]) => ({
      label: getLangLabel(lang, tracks),
      value: `sub:${lang}`,
    })),
);

/** 自动生成的字幕选项 */
const autoOptions = computed(() =>
  Object.entries(props.videoInfo.automatic_captions || {})
    .filter(([lang]) => !FILTERED_KEYS.has(lang))
    .map(([lang, tracks]) => ({
      label: getLangLabel(lang, tracks),
      value: `auto:${lang}`,
    })),
);

/** 合并的分组选项 */
const groupedOptions = computed(() => {
  const groups: { type: "group"; label: string; key: string; children: { label: string; value: string }[] }[] = [];
  if (manualOptions.value.length) {
    groups.push({
      type: "group",
      label: t("detail.subtitlesGroup"),
      key: "manual",
      children: manualOptions.value,
    });
  }
  if (autoOptions.value.length) {
    groups.push({
      type: "group",
      label: t("detail.autoGenerated"),
      key: "auto",
      children: autoOptions.value,
    });
  }
  return groups;
});

const hasSubtitles = computed(() =>
  manualOptions.value.length > 0 || autoOptions.value.length > 0,
);
</script>

<template>
  <n-card :title="$t('detail.subtitles')" size="small">
    <template v-if="hasSubtitles">
      <n-select
        v-model:value="selectedSubtitles"
        :options="groupedOptions"
        multiple
        clearable
        size="small"
        :placeholder="$t('detail.selectSubtitleLangs')"
        max-tag-count="responsive"
      />
    </template>
    <n-text v-else depth="3" style="font-size: 13px">
      {{ $t('detail.noSubtitles') }}
    </n-text>
  </n-card>
</template>
